# Generated by Django 6.0 on 2025-12-26 00:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProcessingConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(default="Default Configuration", max_length=100),
                ),
                ("completed_downloads_path", models.CharField(max_length=500)),
                ("library_base_path", models.CharField(max_length=500)),
                (
                    "calibre_ebook_convert_path",
                    models.CharField(
                        blank=True, default="ebook-convert", max_length=500
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Processing Configuration",
                "verbose_name_plural": "Processing Configurations",
                "ordering": ["-created_at"],
            },
        ),
    ]
