# Generated by Django 6.0 on 2025-12-25 14:28

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("indexers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DownloadAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("object_id", models.UUIDField()),
                ("indexer", models.CharField(max_length=100)),
                ("indexer_id", models.CharField(max_length=100)),
                ("release_title", models.CharField(max_length=500)),
                ("download_url", models.CharField(max_length=1000)),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                (
                    "seeders",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "leechers",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("attempted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("downloading", "Downloading"),
                            ("downloaded", "Downloaded"),
                            ("failed", "Failed"),
                            ("blacklisted", "Blacklisted"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_type", models.CharField(blank=True, max_length=50)),
                ("error_reason", models.TextField(blank=True)),
                (
                    "download_client_download_id",
                    models.CharField(blank=True, max_length=100),
                ),
                ("raw_file_path", models.CharField(blank=True, max_length=1000)),
                (
                    "post_processed_file_path",
                    models.CharField(blank=True, max_length=1000),
                ),
                (
                    "post_process_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "post_process_error_type",
                    models.CharField(blank=True, max_length=50),
                ),
                ("post_process_error_reason", models.TextField(blank=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        limit_choices_to={"model__in": ("book", "audiobook")},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "download_client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="download_attempts",
                        to="indexers.downloadclientconfiguration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Download Attempt",
                "verbose_name_plural": "Download Attempts",
                "ordering": ["-attempted_at"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id", "status"],
                        name="downloaders_d_content_1549d7_idx",
                    ),
                    models.Index(
                        fields=["status"], name="downloaders_d_status_5949df_idx"
                    ),
                    models.Index(
                        fields=["attempted_at"], name="downloaders_d_attempt_908724_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DownloadBlacklist",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("object_id", models.UUIDField()),
                ("indexer", models.CharField(max_length=100)),
                ("indexer_id", models.CharField(max_length=100)),
                ("release_title", models.CharField(max_length=500)),
                ("download_url", models.CharField(max_length=1000)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("failed_download", "Failed Download"),
                            ("wrong_file", "Wrong File"),
                            ("corrupted", "Corrupted"),
                            ("low_quality", "Low Quality"),
                            ("manual", "Manual"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason_details", models.TextField(blank=True)),
                ("blacklisted_at", models.DateTimeField(auto_now_add=True)),
                ("blacklisted_by", models.CharField(blank=True, max_length=50)),
                (
                    "content_type",
                    models.ForeignKey(
                        limit_choices_to={"model__in": ("book", "audiobook")},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Download Blacklist",
                "verbose_name_plural": "Download Blacklist",
                "ordering": ["-blacklisted_at"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="downloaders_d_content_98bca4_idx",
                    ),
                    models.Index(
                        fields=["blacklisted_at"], name="downloaders_d_blackli_4d0a5e_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("content_type", "object_id", "indexer", "indexer_id"),
                        name="unique_blacklist_entry",
                    )
                ],
            },
        ),
    ]
