# Generated by Django 6.0 on 2025-12-25 15:24

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("downloaders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DownloadClientConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "client_type",
                    models.CharField(
                        choices=[("sabnzbd", "SABnzbd")],
                        default="sabnzbd",
                        max_length=20,
                    ),
                ),
                ("host", models.CharField(max_length=255)),
                (
                    "port",
                    models.IntegerField(
                        default=8080,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("use_ssl", models.BooleanField(default=False)),
                ("api_key", models.CharField(max_length=255)),
                ("enabled", models.BooleanField(default=True)),
                ("priority", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Download Client Configuration",
                "verbose_name_plural": "Download Client Configurations",
                "ordering": ["priority", "name"],
            },
        ),
        migrations.RenameIndex(
            model_name="downloadattempt",
            new_name="downloaders_content_c5d54c_idx",
            old_name="downloaders_d_content_1549d7_idx",
        ),
        migrations.RenameIndex(
            model_name="downloadattempt",
            new_name="downloaders_status_260bcf_idx",
            old_name="downloaders_d_status_5949df_idx",
        ),
        migrations.RenameIndex(
            model_name="downloadattempt",
            new_name="downloaders_attempt_3d87c8_idx",
            old_name="downloaders_d_attempt_908724_idx",
        ),
        migrations.RenameIndex(
            model_name="downloadblacklist",
            new_name="downloaders_content_b499a9_idx",
            old_name="downloaders_d_content_98bca4_idx",
        ),
        migrations.RenameIndex(
            model_name="downloadblacklist",
            new_name="downloaders_blackli_69a318_idx",
            old_name="downloaders_d_blackli_4d0a5e_idx",
        ),
        migrations.AlterField(
            model_name="downloadattempt",
            name="download_client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="download_attempts",
                to="downloaders.downloadclientconfiguration",
            ),
        ),
    ]
