# Generated by Django 6.0 on 2025-12-25 14:28

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DownloadClientConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "client_type",
                    models.CharField(
                        choices=[("sabnzbd", "SABnzbd")],
                        default="sabnzbd",
                        max_length=20,
                    ),
                ),
                ("host", models.CharField(max_length=255)),
                (
                    "port",
                    models.IntegerField(
                        default=8080,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("use_ssl", models.BooleanField(default=False)),
                ("api_key", models.CharField(max_length=255)),
                ("enabled", models.BooleanField(default=True)),
                ("priority", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Download Client Configuration",
                "verbose_name_plural": "Download Client Configurations",
                "ordering": ["priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProwlarrConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("host", models.CharField(max_length=255)),
                (
                    "port",
                    models.IntegerField(
                        default=9696,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("api_key", models.CharField(max_length=255)),
                ("use_ssl", models.BooleanField(default=False)),
                ("base_path", models.CharField(blank=True, max_length=500)),
                ("enabled", models.BooleanField(default=True)),
                ("priority", models.IntegerField(default=0)),
                (
                    "timeout",
                    models.IntegerField(
                        default=30,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
            ],
            options={
                "verbose_name": "Prowlarr Configuration",
                "verbose_name_plural": "Prowlarr Configurations",
                "ordering": ["priority", "name"],
            },
        ),
    ]
