# Generated by Django 6.0 on 2025-12-25 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("downloaders", "0002_downloadclientconfiguration_and_more"),
        ("indexers", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DownloadClientConfiguration",
        ),
    ]
