# Generated by Django 6.0 on 2025-12-22 20:18

import django.contrib.postgres.fields
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SearchProvider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("google_books", "Google Books"),
                            ("openlibrary", "OpenLibrary"),
                            ("mangadex", "MangaDex"),
                            ("comicvine", "ComicVine"),
                            ("goodreads", "Goodreads"),
                            ("anilist", "AniList"),
                        ],
                        max_length=50,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("api_key", models.CharField(blank=True, max_length=500)),
                ("base_url", models.URLField(max_length=500)),
                ("priority", models.IntegerField(default=0)),
                (
                    "rate_limit_per_minute",
                    models.IntegerField(
                        default=60,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "supports_media_types",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=20),
                        blank=True,
                        default=list,
                    ),
                ),
                ("config", models.JSONField(blank=True, default=dict)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["priority", "name"],
                "indexes": [
                    models.Index(
                        fields=["provider_type", "enabled"],
                        name="search_sear_provide_4428bc_idx",
                    ),
                    models.Index(
                        fields=["enabled", "priority"],
                        name="search_sear_enabled_8abec7_idx",
                    ),
                ],
            },
        ),
    ]
