# Generated by Django 6.0 on 2025-12-22 20:06

import django.contrib.postgres.fields
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Audiobook",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=500)),
                ("sort_title", models.CharField(blank=True, max_length=500)),
                (
                    "authors",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        default=list,
                    ),
                ),
                ("series", models.CharField(blank=True, max_length=300)),
                (
                    "series_index",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("publication_date", models.DateField(blank=True, null=True)),
                ("added_date", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField(blank=True)),
                (
                    "genres",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                    ),
                ),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                    ),
                ),
                ("identifiers", models.JSONField(blank=True, default=dict)),
                ("cover_url", models.URLField(blank=True, max_length=1000)),
                ("cover_path", models.CharField(blank=True, max_length=1000)),
                ("language", models.CharField(blank=True, max_length=10)),
                ("publisher", models.CharField(blank=True, max_length=300)),
                (
                    "rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("wanted", "Wanted"),
                            ("searching", "Searching"),
                            ("downloading", "Downloading"),
                            ("imported", "Imported"),
                            ("archived", "Archived"),
                        ],
                        default="wanted",
                        max_length=20,
                    ),
                ),
                (
                    "narrators",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        default=list,
                    ),
                ),
                (
                    "duration_seconds",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "bitrate",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "chapters",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
            ],
            options={
                "ordering": ["series", "series_index", "title"],
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=500)),
                ("sort_title", models.CharField(blank=True, max_length=500)),
                (
                    "authors",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        default=list,
                    ),
                ),
                ("series", models.CharField(blank=True, max_length=300)),
                (
                    "series_index",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("publication_date", models.DateField(blank=True, null=True)),
                ("added_date", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField(blank=True)),
                (
                    "genres",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                    ),
                ),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                    ),
                ),
                ("identifiers", models.JSONField(blank=True, default=dict)),
                ("cover_url", models.URLField(blank=True, max_length=1000)),
                ("cover_path", models.CharField(blank=True, max_length=1000)),
                ("language", models.CharField(blank=True, max_length=10)),
                ("publisher", models.CharField(blank=True, max_length=300)),
                (
                    "rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("wanted", "Wanted"),
                            ("searching", "Searching"),
                            ("downloading", "Downloading"),
                            ("imported", "Imported"),
                            ("archived", "Archived"),
                        ],
                        default="wanted",
                        max_length=20,
                    ),
                ),
                ("isbn", models.CharField(blank=True, max_length=13)),
                ("isbn13", models.CharField(blank=True, max_length=13)),
                (
                    "page_count",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("edition", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "ordering": ["series", "series_index", "title"],
            },
        ),
    ]
