# Generated by Django 6.0 on 2025-12-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiobook",
            name="external_id",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="audiobook",
            name="provider",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="book",
            name="external_id",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="book",
            name="provider",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name="audiobook",
            index=models.Index(
                fields=["provider", "external_id"], name="media_audiob_provider_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(
                fields=["provider", "external_id"], name="media_book_provider_idx"
            ),
        ),
    ]
