# Generated by Django 6.0 on 2025-12-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0002_audiobook_external_id_audiobook_provider_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="audiobook",
            name="media_audiob_provider_idx",
        ),
        migrations.RemoveIndex(
            model_name="book",
            name="media_book_provider_idx",
        ),
        migrations.AlterField(
            model_name="audiobook",
            name="status",
            field=models.CharField(
                choices=[
                    ("wanted", "Wanted"),
                    ("searching", "Searching"),
                    ("downloading", "Downloading"),
                    ("downloaded", "Downloaded"),
                    ("post_processed_failed", "Post-Processed Failed"),
                    ("post_processed_success", "Post-Processed Success"),
                    ("archived", "Archived"),
                ],
                default="wanted",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="status",
            field=models.CharField(
                choices=[
                    ("wanted", "Wanted"),
                    ("searching", "Searching"),
                    ("downloading", "Downloading"),
                    ("downloaded", "Downloaded"),
                    ("post_processed_failed", "Post-Processed Failed"),
                    ("post_processed_success", "Post-Processed Success"),
                    ("archived", "Archived"),
                ],
                default="wanted",
                max_length=25,
            ),
        ),
    ]
