# Generated by Django 6.0 on 2025-12-26 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0003_remove_audiobook_media_audiob_provider_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiobook",
            name="library_path",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="book",
            name="library_path",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
